### ISSUE TITLE
Multi byte issue with insert of Danish characters æ ø å

### ISSUE THREAD

**Issue by Laro88** [jtv/libpqxx#240]
I have a regular insert hickup that results in an exception. A 

Snippet from insert function, the problem is the const std::string& Note paramter inserted into $4,
it simply results in an exception when we use the Danish characters æ ø å
We compile in Multi Byte Character Set in VS2017 (and we can't change to unicode until some old components are replaced)

The strangest thing is that we have a unittest that is fine when the test .cpp file is saved as UTF-8, and fails when the file is saved as UTF-8-BOM (this seems awkward / puzzling / counter-intuitive) and I have no explanation.

My guess is that the parameter Note is handled erroneously for some reason in some Multibyte to UTF8 conversion somewhere.
VS gives me an exception in the test: ERROR:  invalid byte sequence for encoding "UTF8": 0xe6 0xf8 0xe5
0xE6 0xf8 0xe5 corresponds to æ ø å in the nordic codepage 865

Any proposals for how to guard against this issue?

```
std::string q = "INSERT INTO trace_dbops (userid, activity, pk, note) VALUES ($1,$2,$3, $4) RETURNING dbopsid";
pqxx::work w(rConnection);
rConnection.prepare("insert_trace_dbops", q);
int userid = I.UserID();
pqxx::result r = w.prepared("insert_trace_dbops")(I.UserID())(Activity)(RelevantPK)(Note).exec();
w.commit();
long pk = r[0][0].as<long>();
return pk;
```

**Comment by tt4g** [comment]
First, source-charset and execution-charset are different in Visual Studio 2017.

* [/source\-charset \(Set Source Character Set\) \| Microsoft Docs](https://docs.microsoft.com/ja-jp/cpp/build/reference/source-charset-set-source-character-set?view=vs-2017)
* [/execution\-charset \(Set Execution Character Set\) \| Microsoft Docs](https://docs.microsoft.com/ja-jp/cpp/build/reference/execution-charset-set-execution-character-set?view=vs-2017)

 If not specified "execution-charset" compiler option, using current code page charset at compile time.
However, The compiler use UTF-8 when found BOM.

[execution\_character\_set pragma \| Microsoft Docs](https://docs.microsoft.com/ja-jp/cpp/preprocessor/execution-character-set?view=vs-2017):

> By default, Visual Studio uses the current code page as the source character set used to interpret your source code for output. When a file is read in, Visual Studio interprets it according to the current code page unless the file code page was set, or unless a byte-order mark (BOM) or UTF-16 characters are detected at the beginning of the file. Because UTF-8 can't be set as the current code page, when the automatic detection encounters source files encoded as UTF-8 without a BOM, Visual Studio assumes that they are encoded by using the current code page. Characters in the source file that are outside the range of the specified or automatically detected code page can cause compiler warnings and errors.

The character encoding of `char` and `wchar_t` is defined as implementation-dependent in the C/C++ specification by C++17 or earlier.
The only guarantee is that the characters provided by the `u8""` literal is interpreted as UTF-8 by C++11 or above.
See also: [c\+\+ \- C standard : Character set and string encoding specification \- Stack Overflow](https://stackoverflow.com/questions/12204453/c-standard-character-set-and-string-encoding-specification)

It is assumed that your problem is caused by "execution-charset" becoming UTF-8 when the source code is UTF-8-BOM.
Since the SQL statements in the source code are compiled into UTF-8 bytecode, I think that a character code error will be reported when code page 865 is mixed.

**Comment by JadeMatrix** [comment]
`æøå` are Unicode code points `U+00E6`, `U+00F8`, `U+00E5`, but this is not their UTF-8 multi-byte representation, which is `0xC3 0xA6 0xC3 0xB8 0xC3 0xA5`.  If your data was UTF-32 the binary data would match the code points (iirc) with zero padding:
```
0x00 0x00 0x00 0xE6 0x00 0x00 0x00 0xF8 0x00 0x00 0x00 0xE5
```
I suspect VS is handling these strings by taking each glyph and casting its code point to `char` to get a byte array (C string), which works for ASCII and that's about it.  You may want to try using a [UTF-8 string literal](https://en.cppreference.com/w/cpp/language/string_literal), and if VS doesn't respect that try loading your string from a file you know is UTF-8 encoded.  Loading from a file may not be a good long-term solution but it'll help pinpoint where the issue is.

**Comment by jtv** [comment]
@tt4g @JadeMatrix thanks for helping out so much.  I don't know how I could keep up without you!

I should add that besides "source" and "execution" encodings, there's also the "client" encoding  — a postgres setting which tells the database in what encoding you want to communicate.  So if you're sending UTF-8, check that the client encoding is also set to match.

**Comment by jtv** [comment]
Has this been resolved now?

**Comment by Laro88** [comment]
The issue is not resolved, however the issue is on our side, we simply have to consider switching to UTF-8 everywhere in our "ecosystem".
Binary streaming would help as mentioned elsewhere, then I could just dump the char* content.

Thank you all for your invaluable help.

**Comment by jtv** [comment]
Thanks for the update.  Going UTF-8 _uniformly across the board_ is definitely the way to go in the general case...

As it happens I was just looking into binary transfers, but there are massive risks with those.  The binary format is not guaranteed to be stable.  The client code and the schema must agree completely on the data types being used, and it may not always be possible to check this.  And until we go C++20, I don't even know that we can check system endianness without incurring undefined behaviour, or do byte swaps portably.
